# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='redis.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bredis.proto\x12\x02pb\".\n\x0e\x46ieldValuePair\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"x\n\x11\x46ieldValuePairMap\x12\x33\n\x07\x66vPairs\x18\x01 \x03(\x0b\x32\".pb.FieldValuePairMap.FvPairsEntry\x1a.\n\x0c\x46vPairsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"W\n\x14RedisTableSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\x12#\n\x07\x66vPairs\x18\x03 \x03(\x0b\x32\x12.pb.FieldValuePair\"2\n\x14RedisTableDelRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\"2\n\x14RedisTableGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\"\x17\n\x15RedisTablePingRequest\"\x1e\n\x1cRedisTableWarmRestartRequest\"%\n\x12RedisTableResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"M\n\x15RedisTableGetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12#\n\x07\x66vPairs\x18\x02 \x03(\x0b\x32\x12.pb.FieldValuePair\")\n\x16RedisTablePingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xce\x01\n\x1dRedisTableWarmRestartResponse\x12\x13\n\x0bwarmRestart\x18\x01 \x01(\x08\x12K\n\rswanRedisData\x18\x02 \x03(\x0b\x32\x34.pb.RedisTableWarmRestartResponse.SwanRedisDataEntry\x1aK\n\x12SwanRedisDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.pb.FieldValuePairMap:\x02\x38\x01\x32\xd7\x02\n\nRedisTable\x12\x39\n\x03Set\x12\x18.pb.RedisTableSetRequest\x1a\x16.pb.RedisTableResponse\"\x00\x12\x39\n\x03\x44\x65l\x12\x18.pb.RedisTableDelRequest\x1a\x16.pb.RedisTableResponse\"\x00\x12<\n\x03Get\x12\x18.pb.RedisTableGetRequest\x1a\x19.pb.RedisTableGetResponse\"\x00\x12?\n\x04Ping\x12\x19.pb.RedisTablePingRequest\x1a\x1a.pb.RedisTablePingResponse\"\x00\x12T\n\x0bWarmRestart\x12 .pb.RedisTableWarmRestartRequest\x1a!.pb.RedisTableWarmRestartResponse\"\x00\x62\x06proto3'
)




_FIELDVALUEPAIR = _descriptor.Descriptor(
  name='FieldValuePair',
  full_name='pb.FieldValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='pb.FieldValuePair.field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='pb.FieldValuePair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=65,
)


_FIELDVALUEPAIRMAP_FVPAIRSENTRY = _descriptor.Descriptor(
  name='FvPairsEntry',
  full_name='pb.FieldValuePairMap.FvPairsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pb.FieldValuePairMap.FvPairsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='pb.FieldValuePairMap.FvPairsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=187,
)

_FIELDVALUEPAIRMAP = _descriptor.Descriptor(
  name='FieldValuePairMap',
  full_name='pb.FieldValuePairMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fvPairs', full_name='pb.FieldValuePairMap.fvPairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FIELDVALUEPAIRMAP_FVPAIRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=187,
)


_REDISTABLESETREQUEST = _descriptor.Descriptor(
  name='RedisTableSetRequest',
  full_name='pb.RedisTableSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pb.RedisTableSetRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table', full_name='pb.RedisTableSetRequest.table', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fvPairs', full_name='pb.RedisTableSetRequest.fvPairs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=276,
)


_REDISTABLEDELREQUEST = _descriptor.Descriptor(
  name='RedisTableDelRequest',
  full_name='pb.RedisTableDelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pb.RedisTableDelRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table', full_name='pb.RedisTableDelRequest.table', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=328,
)


_REDISTABLEGETREQUEST = _descriptor.Descriptor(
  name='RedisTableGetRequest',
  full_name='pb.RedisTableGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pb.RedisTableGetRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table', full_name='pb.RedisTableGetRequest.table', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=380,
)


_REDISTABLEPINGREQUEST = _descriptor.Descriptor(
  name='RedisTablePingRequest',
  full_name='pb.RedisTablePingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=405,
)


_REDISTABLEWARMRESTARTREQUEST = _descriptor.Descriptor(
  name='RedisTableWarmRestartRequest',
  full_name='pb.RedisTableWarmRestartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=437,
)


_REDISTABLERESPONSE = _descriptor.Descriptor(
  name='RedisTableResponse',
  full_name='pb.RedisTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='pb.RedisTableResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=476,
)


_REDISTABLEGETRESPONSE = _descriptor.Descriptor(
  name='RedisTableGetResponse',
  full_name='pb.RedisTableGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='pb.RedisTableGetResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fvPairs', full_name='pb.RedisTableGetResponse.fvPairs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=555,
)


_REDISTABLEPINGRESPONSE = _descriptor.Descriptor(
  name='RedisTablePingResponse',
  full_name='pb.RedisTablePingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='pb.RedisTablePingResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=598,
)


_REDISTABLEWARMRESTARTRESPONSE_SWANREDISDATAENTRY = _descriptor.Descriptor(
  name='SwanRedisDataEntry',
  full_name='pb.RedisTableWarmRestartResponse.SwanRedisDataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pb.RedisTableWarmRestartResponse.SwanRedisDataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='pb.RedisTableWarmRestartResponse.SwanRedisDataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=732,
  serialized_end=807,
)

_REDISTABLEWARMRESTARTRESPONSE = _descriptor.Descriptor(
  name='RedisTableWarmRestartResponse',
  full_name='pb.RedisTableWarmRestartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warmRestart', full_name='pb.RedisTableWarmRestartResponse.warmRestart', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swanRedisData', full_name='pb.RedisTableWarmRestartResponse.swanRedisData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REDISTABLEWARMRESTARTRESPONSE_SWANREDISDATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=807,
)

_FIELDVALUEPAIRMAP_FVPAIRSENTRY.containing_type = _FIELDVALUEPAIRMAP
_FIELDVALUEPAIRMAP.fields_by_name['fvPairs'].message_type = _FIELDVALUEPAIRMAP_FVPAIRSENTRY
_REDISTABLESETREQUEST.fields_by_name['fvPairs'].message_type = _FIELDVALUEPAIR
_REDISTABLEGETRESPONSE.fields_by_name['fvPairs'].message_type = _FIELDVALUEPAIR
_REDISTABLEWARMRESTARTRESPONSE_SWANREDISDATAENTRY.fields_by_name['value'].message_type = _FIELDVALUEPAIRMAP
_REDISTABLEWARMRESTARTRESPONSE_SWANREDISDATAENTRY.containing_type = _REDISTABLEWARMRESTARTRESPONSE
_REDISTABLEWARMRESTARTRESPONSE.fields_by_name['swanRedisData'].message_type = _REDISTABLEWARMRESTARTRESPONSE_SWANREDISDATAENTRY
DESCRIPTOR.message_types_by_name['FieldValuePair'] = _FIELDVALUEPAIR
DESCRIPTOR.message_types_by_name['FieldValuePairMap'] = _FIELDVALUEPAIRMAP
DESCRIPTOR.message_types_by_name['RedisTableSetRequest'] = _REDISTABLESETREQUEST
DESCRIPTOR.message_types_by_name['RedisTableDelRequest'] = _REDISTABLEDELREQUEST
DESCRIPTOR.message_types_by_name['RedisTableGetRequest'] = _REDISTABLEGETREQUEST
DESCRIPTOR.message_types_by_name['RedisTablePingRequest'] = _REDISTABLEPINGREQUEST
DESCRIPTOR.message_types_by_name['RedisTableWarmRestartRequest'] = _REDISTABLEWARMRESTARTREQUEST
DESCRIPTOR.message_types_by_name['RedisTableResponse'] = _REDISTABLERESPONSE
DESCRIPTOR.message_types_by_name['RedisTableGetResponse'] = _REDISTABLEGETRESPONSE
DESCRIPTOR.message_types_by_name['RedisTablePingResponse'] = _REDISTABLEPINGRESPONSE
DESCRIPTOR.message_types_by_name['RedisTableWarmRestartResponse'] = _REDISTABLEWARMRESTARTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FieldValuePair = _reflection.GeneratedProtocolMessageType('FieldValuePair', (_message.Message,), {
  'DESCRIPTOR' : _FIELDVALUEPAIR,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.FieldValuePair)
  })
_sym_db.RegisterMessage(FieldValuePair)

FieldValuePairMap = _reflection.GeneratedProtocolMessageType('FieldValuePairMap', (_message.Message,), {

  'FvPairsEntry' : _reflection.GeneratedProtocolMessageType('FvPairsEntry', (_message.Message,), {
    'DESCRIPTOR' : _FIELDVALUEPAIRMAP_FVPAIRSENTRY,
    '__module__' : 'redis_pb2'
    # @@protoc_insertion_point(class_scope:pb.FieldValuePairMap.FvPairsEntry)
    })
  ,
  'DESCRIPTOR' : _FIELDVALUEPAIRMAP,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.FieldValuePairMap)
  })
_sym_db.RegisterMessage(FieldValuePairMap)
_sym_db.RegisterMessage(FieldValuePairMap.FvPairsEntry)

RedisTableSetRequest = _reflection.GeneratedProtocolMessageType('RedisTableSetRequest', (_message.Message,), {
  'DESCRIPTOR' : _REDISTABLESETREQUEST,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTableSetRequest)
  })
_sym_db.RegisterMessage(RedisTableSetRequest)

RedisTableDelRequest = _reflection.GeneratedProtocolMessageType('RedisTableDelRequest', (_message.Message,), {
  'DESCRIPTOR' : _REDISTABLEDELREQUEST,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTableDelRequest)
  })
_sym_db.RegisterMessage(RedisTableDelRequest)

RedisTableGetRequest = _reflection.GeneratedProtocolMessageType('RedisTableGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _REDISTABLEGETREQUEST,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTableGetRequest)
  })
_sym_db.RegisterMessage(RedisTableGetRequest)

RedisTablePingRequest = _reflection.GeneratedProtocolMessageType('RedisTablePingRequest', (_message.Message,), {
  'DESCRIPTOR' : _REDISTABLEPINGREQUEST,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTablePingRequest)
  })
_sym_db.RegisterMessage(RedisTablePingRequest)

RedisTableWarmRestartRequest = _reflection.GeneratedProtocolMessageType('RedisTableWarmRestartRequest', (_message.Message,), {
  'DESCRIPTOR' : _REDISTABLEWARMRESTARTREQUEST,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTableWarmRestartRequest)
  })
_sym_db.RegisterMessage(RedisTableWarmRestartRequest)

RedisTableResponse = _reflection.GeneratedProtocolMessageType('RedisTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _REDISTABLERESPONSE,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTableResponse)
  })
_sym_db.RegisterMessage(RedisTableResponse)

RedisTableGetResponse = _reflection.GeneratedProtocolMessageType('RedisTableGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _REDISTABLEGETRESPONSE,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTableGetResponse)
  })
_sym_db.RegisterMessage(RedisTableGetResponse)

RedisTablePingResponse = _reflection.GeneratedProtocolMessageType('RedisTablePingResponse', (_message.Message,), {
  'DESCRIPTOR' : _REDISTABLEPINGRESPONSE,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTablePingResponse)
  })
_sym_db.RegisterMessage(RedisTablePingResponse)

RedisTableWarmRestartResponse = _reflection.GeneratedProtocolMessageType('RedisTableWarmRestartResponse', (_message.Message,), {

  'SwanRedisDataEntry' : _reflection.GeneratedProtocolMessageType('SwanRedisDataEntry', (_message.Message,), {
    'DESCRIPTOR' : _REDISTABLEWARMRESTARTRESPONSE_SWANREDISDATAENTRY,
    '__module__' : 'redis_pb2'
    # @@protoc_insertion_point(class_scope:pb.RedisTableWarmRestartResponse.SwanRedisDataEntry)
    })
  ,
  'DESCRIPTOR' : _REDISTABLEWARMRESTARTRESPONSE,
  '__module__' : 'redis_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedisTableWarmRestartResponse)
  })
_sym_db.RegisterMessage(RedisTableWarmRestartResponse)
_sym_db.RegisterMessage(RedisTableWarmRestartResponse.SwanRedisDataEntry)


_FIELDVALUEPAIRMAP_FVPAIRSENTRY._options = None
_REDISTABLEWARMRESTARTRESPONSE_SWANREDISDATAENTRY._options = None

_REDISTABLE = _descriptor.ServiceDescriptor(
  name='RedisTable',
  full_name='pb.RedisTable',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=810,
  serialized_end=1153,
  methods=[
  _descriptor.MethodDescriptor(
    name='Set',
    full_name='pb.RedisTable.Set',
    index=0,
    containing_service=None,
    input_type=_REDISTABLESETREQUEST,
    output_type=_REDISTABLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Del',
    full_name='pb.RedisTable.Del',
    index=1,
    containing_service=None,
    input_type=_REDISTABLEDELREQUEST,
    output_type=_REDISTABLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='pb.RedisTable.Get',
    index=2,
    containing_service=None,
    input_type=_REDISTABLEGETREQUEST,
    output_type=_REDISTABLEGETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='pb.RedisTable.Ping',
    index=3,
    containing_service=None,
    input_type=_REDISTABLEPINGREQUEST,
    output_type=_REDISTABLEPINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WarmRestart',
    full_name='pb.RedisTable.WarmRestart',
    index=4,
    containing_service=None,
    input_type=_REDISTABLEWARMRESTARTREQUEST,
    output_type=_REDISTABLEWARMRESTARTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDISTABLE)

DESCRIPTOR.services_by_name['RedisTable'] = _REDISTABLE

# @@protoc_insertion_point(module_scope)
