# framewave packages

FRAMEWAVE = framewave_1.0_$(CONFIGURED_ARCH).deb
$(FRAMEWAVE)_SRC_PATH = $(SRC_PATH)/framewave
$(FRAMEWAVE)_DEPENDS += $(LIBSWSSCOMMON_DEV) $(LIBHIREDIS_DEV) $(LIBSAIMETADATA_DEV)
$(FRAMEWAVE)_RDEPENDS += $(LIBSWSSCOMMON) $(LIBHIREDIS) $(LIBSAIMETADATA)
SONIC_MAKE_DEBS += $(FRAMEWAVE)