# framewave packages

FRAMEWAVE_PROXY = framewave-proxy_1.0_$(CONFIGURED_ARCH).deb
$(FRAMEWAVE_PROXY)_SRC_PATH = $(SRC_PATH)/framewave
$(FRAMEWAVE_PROXY)_DEPENDS += $(LIBSWSSCOMMON_DEV) $(LIBHIREDIS_DEV) $(LIBSAIMETADATA_DEV)
$(FRAMEWAVE_PROXY)_RDEPENDS += $(LIBSWSSCOMMON) $(LIBHIREDIS) $(LIBSAIMETADATA)
SONIC_MAKE_DEBS += $(FRAMEWAVE_PROXY)